[tool.poetry]
name = "{{ cookiecutter.project_name }}"
version = "0.0.1"
description = "{{ cookiecutter.project_description }}"
authors = ["Your Name"]

[tool.poetry.dependencies]
python = "^{{ cookiecutter.python_version }}"
yanga = "*"
west = "*"
